/**
 * IoT Sensor Data
 * This is a sample data provider to mimick IoT data logger
 *
 * OpenAPI spec version: 1.0.0
 * Contact: romina.kehl@me.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Sensor {
    id?: number;
    name?: string;
    type?: string;
}
